# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       libdaemon

# >> macros
# << macros

Summary:    Library for writing UNIX daemons
Version:    0.14
Release:    1
Group:      System/Libraries
License:    LGPLv2
URL:        http://0pointer.de/lennart/projects/libdaemon/
Source0:    %{name}-%{version}.tar.xz
Source100:  libdaemon.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description
libdaemon is a lightweight C library which eases the writing of UNIX daemons.
It consists of the following parts:
* A wrapper around fork() which does the correct daemonization
  procedure of a process
* A wrapper around syslog() for simpler and compatible log output to
  Syslog or STDERR
* An API for writing PID files
* An API for serializing UNIX signals into a pipe for usage with
  select() or poll()
* An API for running subprocesses with STDOUT and STDERR redirected
  to syslog.


%package devel
Summary:    Libraries and header files for libdaemon development
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The %{name}-devel package contains the header files and libraries
necessary for developing programs using libdaemon.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --disable-lynx

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
find $RPM_BUILD_ROOT \( -name *.a -o -name *.la \) -exec rm {} \;

#rm $RPM_BUILD_ROOT/%{_datadir}/doc/libdaemon/README
rm $RPM_BUILD_ROOT/%{_datadir}/doc/libdaemon/README.html
rm $RPM_BUILD_ROOT/%{_datadir}/doc/libdaemon/style.css
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc LICENSE
%{_libdir}/*so.*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%doc doc/README.html doc/style.css
%{_includedir}/*
%{_libdir}/*.so
%{_libdir}/pkgconfig/*.pc
# >> files devel
# << files devel
